# Generated by Django 5.1.3 on 2025-01-11 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="EnergyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
                (
                    "symbol",
                    models.ImageField(
                        blank=True, null=True, upload_to="energy_symbols/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.TextField()),
                ("damage", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Rarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="card_illustrations/"
                    ),
                ),
                (
                    "card_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ccapp.cardtype"
                    ),
                ),
                ("moves", models.ManyToManyField(to="ccapp.move")),
                (
                    "rarity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ccapp.rarity"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="collection_illustrations/"
                    ),
                ),
                ("cards", models.ManyToManyField(to="ccapp.card")),
            ],
        ),
        migrations.CreateModel(
            name="MoveEnergyRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "energy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ccapp.energytype",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ccapp.move"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="move",
            name="energy_requirements",
            field=models.ManyToManyField(
                through="ccapp.MoveEnergyRequirement", to="ccapp.energytype"
            ),
        ),
    ]
