# Generated by Django 5.1.3 on 2025-01-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccapp", "0002_ability_card_ability"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name="card",
            name="stage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ccapp.cardstage",
            ),
            preserve_default=False,
        ),
    ]
