# Generated by Django 5.1.3 on 2025-01-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccapp", "0004_card_hitpoints_user_usercard_user_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
