# Generated by Django 5.1.3 on 2025-01-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccapp", "0005_user_experience_user_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="available_packs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="last_refresh",
            field=models.DateTimeField(null=True),
        ),
    ]
