# Generated by Django 5.1.3 on 2025-01-22 11:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccapp", "0006_user_available_packs_user_last_refresh"),
    ]

    operations = [
        migrations.CreateModel(
            name="Illustrator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="ProfilePicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="profile_pictures/")),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="pack_hourglasses",
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name="user",
            name="time_to_next_refresh",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="card",
            name="illustrator",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="ccapp.illustrator",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ccapp.profilepicture",
            ),
        ),
    ]
