# Generated by Django 5.1.3 on 2025-01-24 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccapp", "0007_illustrator_profilepicture_user_pack_hourglasses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="dex_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="evolves_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ccapp.card",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="is_ex",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Binder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="binder_covers/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BinderSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_number", models.PositiveIntegerField()),
                (
                    "binder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="ccapp.binder",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ccapp.card"
                    ),
                ),
            ],
            options={
                "unique_together": {("binder", "slot_number")},
            },
        ),
    ]
